/* my_cgi.c */
#include <stdio.h>
#include <time.h>

int main() {
    time_t t;
    time(&t);
    
    // CGI 프로그램은 HTML 형태의 출력을 내보내야 함
    printf("<h1>Welcome to CGI Program</h1>\n");
    printf("<p>Current Server Time: %s</p>\n", ctime(&t));
    printf("<p>This content is generated by C program.</p>\n");
    
    return 0;
}
